# 站点设置
title: 喜欢悠然自得
SEOTitle: 喜欢悠然自得 | Blog
header-img: img/post-bg-desk.jpg
email: hemuyang666@gmail.com
description: "I like to be leisurely and carefree"
keyword: "喜欢悠然自得, Blog, 技术博客, 个人博客, Jekyll 主题, 计算机技术,游戏,悠然,沐阳"
url: "http://p0m1se.club/"          # 你的主机，用于绝对 URL
baseurl: ""      # 例如，如果博客托管在 'host/blog'，则设置为 '/blog'
github_repo: "https://github.com/YouRan4/YouRan4.github.io.git" # 你的代码仓库

# 侧边栏设置
sidebar: true                           # 是否使用侧边栏。
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about.png     # 使用绝对 URL，因为它在 `/` 和 `/about/` 中都被使用


# 社交网络设置
RSS: false
# weibo_username:     youran4
# zhihu_username:     youran4
github_username:    youran4
# facebook_username:  youran4
# jianshu_username:   youran4
#twitter_username:   youran4




# 构建设置
# 从 2016 年起，GitHub Pages 不再支持 'pygments'。改用 'rouge' 进行代码高亮。
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # 如果你想自定义锚点，请查看 `post.html` 的第 181 行



# Gems（插件）
# Jekyll 3.5.0+ 推荐使用 plugins 替代 gems
plugins: [jekyll-paginate]




# Markdown 设置
# 将 redcarpet 替换为 kramdown，
# 虽然 redcarpet 可以自动高亮代码，但缺少 header-id 会使目录功能不可用，所以我改用 kramdown
# 文档: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # 使用 Github Flavored Markdown（非常重要）



# 评论系统
# Gitalk
gitalk:
  enable: true    # 是否开启 Gitalk 评论
  clientID: $GITALK_CLIENT_ID                   # 从 GitHub secrets 读取
  clientSecret: $GITALK_CLIENT_SECRET           # 从 GitHub secrets 读取
  repo: YouRan4.github.io    # 仓库名称
  owner: YouRan4    # GitHub 用户名
  admin: YouRan4
  distractionFreeMode: true # 是否启用类似 Facebook 的阴影遮罩

# 统计

# Analytics 设置
# 百度统计
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_enable: false          # 是否启用 Google Analytics
# ga_track_id: 'G-7J7YNG0W9V'            # 格式: UA-xxxxxx-xx
# ga_domain: auto               # 默认是 auto，这里我自定义了域名，如果你没有自己的域名，需要改成 auto





# 精选标签
featured-tags: true                     # 是否在首页显示标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# 渐进式 Web 应用（PWA）
chrome-tab-theme-color: "#000000"
service-worker: true



# 友情链接
friends: [
    {
        title: "GitHub",
        href: "http://github.com"
    }
]
